services:

  drf-project:
    container_name: drf-project
    image: drf-project
    volumes:
      - ./drf_project:/drf_project
    build:
      context: .
      dockerfile: ./docker/drf-project/Dockerfile
    ports:
      - "8000:8000"

  redis:
    container_name: redis
    image: redis
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    hostname: redis
    ports:
      - "6379:6379"
