# Generated by Django 5.1 on 2024-08-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(max_length=75)),
                ('rus_word', models.CharField(max_length=75)),
            ],
        ),
    ]
